### ISSUE TITLE
compile

### ISSUE THREAD

**Issue by ezekel** [vkdinventor/MyVlcPlayer#2]
HI @vkdinventor ,

can I ask some help please how did you compile the libvlc for android?

also how can I run your project I would like to test on my device.

Thank you.

**Comment by ezekel** [comment]
@vkdinventor ,

HI I tested  in
`
         minSdkVersion 17
        targetSdkVersion 25  `

its not working

**Comment by vkdinventor** [comment]
Hi @ezekel 
No I didn't compile libvlc. I have used prebuild binary from https://github.com/maruku/libvlc 
Yes You can run this project on your device. This project is build on Android Studio.

Note: this app is supported on only armeabi-v7a devices.
