### ISSUE TITLE
:libvlc:buildDebugARMv7 FAILED

### ISSUE THREAD

**Issue by ezekel** [vkdinventor/MyVlcPlayer#3]
can I ask help please in building manually, I tried to manually compile the vlc which I pull from there repo
`git clone https://code.videolan.org/videolan/vlc-android.git`

when i tried to build in the gradle it gives me this error
![libvlcfailed](https://cloud.githubusercontent.com/assets/6830057/20585465/4596c1d2-b236-11e6-96f5-3bbb9eee9706.png)

is there something that I need to install ?

Thank you in advance.

**Comment by vkdinventor** [comment]
please see this http://stackoverflow.com/a/30350687/2579281
