### ISSUE TITLE
Don't get thumbnail??

### ISSUE THREAD

**Issue by nguyenthoai** [vkdinventor/MyVlcPlayer#4]
code:  byte[] data = libvlc.getThumbnail(videoPath, 200, 200);
data null????

**Comment by vkdinventor** [comment]
can you show me logcat please.

**Comment by nguyenthoai** [comment]
I add a button "Capture", when i click the button, i will call me thod "libvlc.getThumbnail".

Here code MainActivity:
package com.vikash.example.myvlcplayer;

import android.app.Activity;
import android.app.ProgressDialog;
import android.content.res.Configuration;
import android.graphics.PixelFormat;
import android.net.Uri;
import android.os.Bundle;
import android.os.Handler;
import android.util.Log;
import android.view.SurfaceHolder;
import android.view.SurfaceView;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.ProgressBar;

import org.videolan.libvlc.IVideoPlayer;
import org.videolan.libvlc.LibVLC;
import org.videolan.libvlc.LibVlcUtil;

import java.io.File;
import java.io.FileReader;
import java.util.ArrayList;


public class MainActivity extends Activity implements SurfaceHolder.Callback, IVideoPlayer {


    // Display Surface

    private SurfaceView mSurface;
    private SurfaceHolder holder;

    // Overlay / Controls

    // media player
    private LibVLC libvlc;
    private int mVideoWidth;
    private int mVideoHeight;
    private final static int VideoSizeChanged = -1;
    private ProgressBar mSpinner;
    private String videoPath="https://archive.org/download/Popeye_forPresident/Popeye_forPresident_512kb.mp4";

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        mSurface = (SurfaceView) findViewById(R.id.vlc_surface);
        mSpinner = (ProgressBar) findViewById(R.id.spinner);
        mSpinner.setVisibility(View.VISIBLE);
        playMovie();
        new Handler().postDelayed(new Runnable() {
            @Override
            public void run() {
                mSpinner.setVisibility(View.GONE);
            }
        }, 2000);


        Button cap = (Button) findViewById(R.id.cap);
        cap.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                byte[] data = libvlc.getThumbnail(videoPath, mVideoWidth, mVideoHeight);
                if (data == null) {
                    Log.e("MainActivity", "null ");
                } else {
                    Log.e("MainActivity", "data--->" + data.length);
                }
            }
        });
    }


    public void playMovie() {
        if (libvlc != null && libvlc.isPlaying())
            return;
        holder = mSurface.getHolder();
        holder.addCallback(this);
        createPlayer(videoPath);
    }


    @Override
    public void onConfigurationChanged(Configuration newConfig) {
        super.onConfigurationChanged(newConfig);
        setSize(mVideoWidth, mVideoHeight);
    }

    @Override
    protected void onResume() {

        super.onResume();
    }

    @Override
    protected void onPause() {
        super.onPause();
        //releasePlayer();
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        releasePlayer();
    }

    /**
     * **********
     * Surface
     * ***********
     */

    public void surfaceCreated(SurfaceHolder holder) {
//        byte[] data = libvlc.getThumbnail(videoPath, 200, 200);
//        if (data == null) {
//            Log.e("MainActivity", "null cmnr");
//        } else {
//            Log.e("MainActivity", "data--->" + data.length);
//        }
    }

    public void surfaceChanged(SurfaceHolder surfaceholder, int format,
                               int width, int height) {
        if (libvlc != null)
            libvlc.attachSurface(surfaceholder.getSurface(), this);
    }

    public void surfaceDestroyed(SurfaceHolder surfaceholder) {
    }

    private void setSize(int width, int height) {
        mVideoWidth = width;
        mVideoHeight = height;
        if (mVideoWidth * mVideoHeight <= 1)
            return;

        // get screen size
        int w = getWindow().getDecorView().getWidth();
        int h = getWindow().getDecorView().getHeight();

        // getWindow().getDecorView() doesn't always take orientation into
        // account, we have to correct the values
        boolean isPortrait = getResources().getConfiguration().orientation == Configuration.ORIENTATION_PORTRAIT;
        if (w > h && isPortrait || w < h && !isPortrait) {
            int i = w;
            w = h;
            h = i;
        }

        float videoAR = (float) mVideoWidth / (float) mVideoHeight;
        float screenAR = (float) w / (float) h;

        if (screenAR < videoAR)
            h = (int) (w / videoAR);
        else
            w = (int) (h * videoAR);

        // force surface buffer size
        if (holder != null)
            holder.setFixedSize(mVideoWidth, mVideoHeight);

        // set display size
        ViewGroup.LayoutParams lp = mSurface.getLayoutParams();
        lp.width = w;
        lp.height = h;
        mSurface.setLayoutParams(lp);
        mSurface.invalidate();
    }

    @Override
    public void setSurfaceSize(int width, int height, int visible_width,
                               int visible_height, int sar_num, int sar_den) {
    }


    private void createPlayer(String media) {
        releasePlayer();
        try {
            // Create a new media player
            libvlc = LibVLC.getInstance();
            libvlc.setHardwareAcceleration(LibVLC.HW_ACCELERATION_FULL);
            libvlc.eventVideoPlayerActivityCreated(true);
            libvlc.setSubtitlesEncoding("");
            libvlc.setAout(LibVLC.AOUT_OPENSLES);
            libvlc.setTimeStretching(true);
            libvlc.setChroma("RV32");
            libvlc.setVerboseMode(true);

//            ArrayList<String> options = new ArrayList<String>();
//            //options.add("--subsdec-encoding <encoding>");
//            options.add("--aout=opensles");
//            options.add("--audio-time-stretch"); // time stretching
//            options.add("-vvv"); // verbosity
//            libvlc2 = new LibVLC(options);

            LibVLC.restart(this);
            holder.setFormat(PixelFormat.RGBX_8888);
            holder.setKeepScreenOn(true);
            libvlc.playMRL(LibVLC.PathToURI(media));
        } catch (Exception e) {
            Log.v("MyVlc", "Could not create Vlc Player");
        }
    }

    private void releasePlayer() {
        if (libvlc == null)
            return;
        libvlc.stop();
        libvlc.detachSurface();
        holder = null;
        libvlc.closeAout();

        mVideoWidth = 0;
        mVideoHeight = 0;
    }

    @Override
    public void onStart() {
        super.onStart();
    }

    @Override
    public void onStop() {
        super.onStop();

    }
}

**Comment by nguyenthoai** [comment]
help me!!

**Comment by vkdinventor** [comment]
I will surely help as soon as I get time.

**Comment by vkdinventor** [comment]
Hello
This problem is because of libvlc. please see this issue.
https://forum.videolan.org/viewtopic.php?t=122963

getThumbnail() method is moved to VLCUtil class in newer vesrion. see this
https://mailman.videolan.org/pipermail/android/2015-May/007345.html 
https://code.videolan.org/videolan/vlc-android/commit/b943544db27ca4c5d31c803acf1cfd7bafd5d080

**Comment by nguyenthoai** [comment]
Hi,
How get image from video? or How play link rtsp on TextureView?
Thank you :D

2016-11-30 17:04 GMT+07:00 vikash <notifications@github.com>:

**Comment by vkdinventor** [comment]
just place your rtsp ulr in place of http url and enjoy.
