### ISSUE TITLE
Problem Android 6.0.1

### ISSUE THREAD

**Issue by azzahrah** [vkdinventor/MyVlcPlayer#5]
helo

I have problem compile for android 6.0.1 with hardware 64Bit, 

Client not ready yet..Waiting for process to come online
Connected to process 7989 on device amlogic-x96-192.168.0.101:5555
I/OpenGLRenderer: Initialized EGL, version 1.4
V/RenderScript: 0xe11a1000 Launching thread(s), CPUs 4
E/ContentValues: Key down, code 23
E/ContentValues: Key up, code 23
E/linker: /data/app/com.centratelemedia.iptvplayer-1/lib/arm/libvlcjni.so: has text relocations
E/VLC/LibVLC: Can't load vlcjni library: java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/com.centratelemedia.iptvplayer-1/lib/arm/libvlcjni.so: has text relocations
I/art: System.exit called, status: 1
I/AndroidRuntime: VM exiting with result code 1, cleanup skipped.
Application terminated.

**Comment by vkdinventor** [comment]
Hi please follow https://wiki.videolan.org/AndroidCompile and and compile libvlc and then use generated .so. It will solve your issue.
