### ISSUE TITLE
libvlcjni.so: has text relocations

### ISSUE THREAD

**Issue by hiro2016** [vkdinventor/MyVlcPlayer#7]
It's probably your NDK version as discussed here: http://stackoverflow.com/questions/32346402/libavcodec-so-has-text-relocations

Your app compiles and installs itself fine but does not run.
Android version 6.0.1
Nexus 7
```

d@d:~/AndroidStudioProjects/MyVlcPlayer/app/src/main/jniLibs/armeabi-v7a$ adb shell getprop ro.product.cpu.abi
armeabi-v7a
```

I did the check and yes it contains a TEXTREL.

    d@d:~/AndroidStudioProjects/MyVlcPlayer/app/src/main/jniLibs/armeabi-v7a$ readelf -a libvlcjni.so|grep TEXTREL
     0x00000016 (TEXTREL)                    0x0
     0x0000001e (FLAGS)                      SYMBOLIC TEXTREL BIND_NOW

Logcat:

    03-23 19:55:57.555 16488-16488/? I/art: Late-enabling -Xcheck:jni
    03-23 19:55:57.611 16488-16488/? W/ActivityThread: Application com.vikash.example.myvlcplayer is waiting for the debugger on port 8100...
    03-23 19:55:57.612 16488-16488/? I/System.out: Sending WAIT chunk
    03-23 19:55:57.867 16488-16508/com.vikash.example.myvlcplayer I/art: Debugger is active
    03-23 19:55:58.013 16488-16488/com.vikash.example.myvlcplayer I/System.out: Debugger has connected
    03-23 19:55:58.013 16488-16488/com.vikash.example.myvlcplayer I/System.out: waiting for debugger to settle...
    03-23 19:55:58.213 16488-16488/com.vikash.example.myvlcplayer I/System.out: waiting for debugger to settle...
    03-23 19:55:58.413 16488-16488/com.vikash.example.myvlcplayer I/System.out: waiting for debugger to settle...
    03-23 19:55:58.614 16488-16488/com.vikash.example.myvlcplayer I/System.out: waiting for debugger to settle...
    03-23 19:55:58.814 16488-16488/com.vikash.example.myvlcplayer I/System.out: waiting for debugger to settle...
    03-23 19:55:59.015 16488-16488/com.vikash.example.myvlcplayer I/System.out: waiting for debugger to settle...
    03-23 19:55:59.215 16488-16488/com.vikash.example.myvlcplayer I/System.out: waiting for debugger to settle...
    03-23 19:55:59.416 16488-16488/com.vikash.example.myvlcplayer I/System.out: waiting for debugger to settle...
    03-23 19:55:59.616 16488-16488/com.vikash.example.myvlcplayer I/System.out: debugger has settled (1300)
    03-23 19:55:59.716 16488-16488/com.vikash.example.myvlcplayer W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm --instruction-set-features=smp,div,atomic_ldrd_strd --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=krait --instruction-set-features=default --dex-file=/data/app/com.vikash.example.myvlcplayer-1/split_lib_dependencies_apk.apk --oat-file=/data/dalvik-cache/arm/data@app@com.vikash.example.myvlcplayer-1@split_lib_dependencies_apk.apk@classes.dex) because non-0 exit status
    03-23 19:55:59.944 16488-16488/com.vikash.example.myvlcplayer W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm --instruction-set-features=smp,div,atomic_ldrd_strd --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=krait --instruction-set-features=default --dex-file=/data/app/com.vikash.example.myvlcplayer-1/split_lib_slice_0_apk.apk --oat-file=/data/dalvik-cache/arm/data@app@com.vikash.example.myvlcplayer-1@split_lib_slice_0_apk.apk@classes.dex) because non-0 exit status
    03-23 19:56:00.006 16488-16488/com.vikash.example.myvlcplayer W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm --instruction-set-features=smp,div,atomic_ldrd_strd --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=krait --instruction-set-features=default --dex-file=/data/app/com.vikash.example.myvlcplayer-1/split_lib_slice_1_apk.apk --oat-file=/data/dalvik-cache/arm/data@app@com.vikash.example.myvlcplayer-1@split_lib_slice_1_apk.apk@classes.dex) because non-0 exit status
    03-23 19:56:00.086 16488-16488/com.vikash.example.myvlcplayer W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm --instruction-set-features=smp,div,atomic_ldrd_strd --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=krait --instruction-set-features=default --dex-file=/data/app/com.vikash.example.myvlcplayer-1/split_lib_slice_2_apk.apk --oat-file=/data/dalvik-cache/arm/data@app@com.vikash.example.myvlcplayer-1@split_lib_slice_2_apk.apk@classes.dex) because non-0 exit status
    03-23 19:56:00.143 16488-16488/com.vikash.example.myvlcplayer W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm --instruction-set-features=smp,div,atomic_ldrd_strd --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=krait --instruction-set-features=default --dex-file=/data/app/com.vikash.example.myvlcplayer-1/split_lib_slice_3_apk.apk --oat-file=/data/dalvik-cache/arm/data@app@com.vikash.example.myvlcplayer-1@split_lib_slice_3_apk.apk@classes.dex) because non-0 exit status
    03-23 19:56:00.202 16488-16488/com.vikash.example.myvlcplayer W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm --instruction-set-features=smp,div,atomic_ldrd_strd --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=krait --instruction-set-features=default --dex-file=/data/app/com.vikash.example.myvlcplayer-1/split_lib_slice_4_apk.apk --oat-file=/data/dalvik-cache/arm/data@app@com.vikash.example.myvlcplayer-1@split_lib_slice_4_apk.apk@classes.dex) because non-0 exit status
    03-23 19:56:00.278 16488-16488/com.vikash.example.myvlcplayer W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm --instruction-set-features=smp,div,atomic_ldrd_strd --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=krait --instruction-set-features=default --dex-file=/data/app/com.vikash.example.myvlcplayer-1/split_lib_slice_5_apk.apk --oat-file=/data/dalvik-cache/arm/data@app@com.vikash.example.myvlcplayer-1@split_lib_slice_5_apk.apk@classes.dex) because non-0 exit status
    03-23 19:56:00.337 16488-16488/com.vikash.example.myvlcplayer W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm --instruction-set-features=smp,div,atomic_ldrd_strd --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=krait --instruction-set-features=default --dex-file=/data/app/com.vikash.example.myvlcplayer-1/split_lib_slice_6_apk.apk --oat-file=/data/dalvik-cache/arm/data@app@com.vikash.example.myvlcplayer-1@split_lib_slice_6_apk.apk@classes.dex) because non-0 exit status
    03-23 19:56:00.397 16488-16488/com.vikash.example.myvlcplayer W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm --instruction-set-features=smp,div,atomic_ldrd_strd --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=krait --instruction-set-features=default --dex-file=/data/app/com.vikash.example.myvlcplayer-1/split_lib_slice_7_apk.apk --oat-file=/data/dalvik-cache/arm/data@app@com.vikash.example.myvlcplayer-1@split_lib_slice_7_apk.apk@classes.dex) because non-0 exit status
    03-23 19:56:00.473 16488-16488/com.vikash.example.myvlcplayer W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm --instruction-set-features=smp,div,atomic_ldrd_strd --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=krait --instruction-set-features=default --dex-file=/data/app/com.vikash.example.myvlcplayer-1/split_lib_slice_8_apk.apk --oat-file=/data/dalvik-cache/arm/data@app@com.vikash.example.myvlcplayer-1@split_lib_slice_8_apk.apk@classes.dex) because non-0 exit status
    03-23 19:56:00.536 16488-16488/com.vikash.example.myvlcplayer W/art: Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --debuggable --instruction-set=arm --instruction-set-features=smp,div,atomic_ldrd_strd --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=krait --instruction-set-features=default --dex-file=/data/app/com.vikash.example.myvlcplayer-1/split_lib_slice_9_apk.apk --oat-file=/data/dalvik-cache/arm/data@app@com.vikash.example.myvlcplayer-1@split_lib_slice_9_apk.apk@classes.dex) because non-0 exit status
    03-23 19:56:00.637 16488-16488/com.vikash.example.myvlcplayer E/linker: /data/app/com.vikash.example.myvlcplayer-1/lib/arm/libvlcjni.so: has text relocations
    03-23 19:56:00.638 16488-16488/com.vikash.example.myvlcplayer E/VLC/LibVLC: Can't load vlcjni library: java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/com.vikash.example.myvlcplayer-1/lib/arm/libvlcjni.so: has text relocations
    03-23 19:56:00.643 16488-16488/com.vikash.example.myvlcplayer I/art: System.exit called, status: 1
    03-23 19:56:00.643 16488-16488/com.vikash.example.myvlcplayer I/AndroidRuntime: VM exiting with result code 1, cleanup skipped.

**Comment by ruudsieb** [comment]
I got it to work by setting sdk version in gradle to 21. After reading this: https://stackoverflow.com/questions/37360464/libiconv-so-has-text-relocations
