### ISSUE TITLE
can we play rtsp stream with the project?

### ISSUE THREAD

**Issue by luvjennifer** [vkdinventor/MyVlcPlayer#8]
hi, nice work and thank you!
I cloned your project and would like to play rtsp stream (rtsp://mpv.cdn3.bigCDN.com:554/bigCDN/_definst_/mp4:bigbuckbunnyiphone_400.mp4) with this. but I have no luck. I kind of modify the createPlayer function to meet my needs as below.  please help!

`
  private void createPlayer(String media) {
        releasePlayer();
        try {
            // Create a new media player
            libvlc = LibVLC.getInstance();
            libvlc.setHardwareAcceleration(LibVLC.HW_ACCELERATION_FULL);
            //libvlc.setHardwareAcceleration(LibVLC.HW_ACCELERATION_DISABLED);
            libvlc.eventVideoPlayerActivityCreated(true);
            libvlc.setSubtitlesEncoding("");
            libvlc.setAout(LibVLC.AOUT_OPENSLES);
            libvlc.setTimeStretching(true);
            libvlc.setChroma("RV32");
            libvlc.setVerboseMode(true);
            LibVLC.restart(this);
            holder.setFormat(PixelFormat.RGBX_8888);
            holder.setKeepScreenOn(true);
            //libvlc.playMRL(LibVLC.PathToURI(media));

            //try rtsp stream
            libvlc.setMediaList();
            Media rtspmedia = new Media( libvlc, media);
            libvlc.getMediaList().add(rtspmedia);
            libvlc.playIndex(libvlc.getMediaList().size() - 1);

        } catch (Exception e) {
            Log.v("MyVlc", "Could not create Vlc Player");
        }
    }`

**Comment by vkdinventor** [comment]
Did you try 
libvlc.playMRL("Your rtsp url here");
